execution:
  checkpointing:
    interval: 10min
blob:
  server:
    port: '6124'
taskmanager:
  memory:
    process:
      size: 2048m
  numberOfTaskSlots: 20
jobmanager:
  rpc:
    address: jobmanager
  memory:
    process:
      size: 4096m
query:
  server:
    port: '6125'
