<pattern> ::= <events> <withinClause> | <events>
<withinClause> ::= <fNum>
<events> ::= <event> | <events> <event>
<event> ::= <eConcat> <identifier> <conditions> <quantifier>
<eConcat> ::= next | followedBy | followedByAny
<identifier> ::= id1
<conditions> ::= <condition> | <conditions> <condition>
<condition> ::= <cConcat> <var> <op> <fNum>
<cConcat> ::= and | or
<op> ::= equal | notEqual | lt | gt
<var> ::= v1 | v2
<quantifier> ::= oneOrMore | optional | <iNum>
<iNum> ::= <digit> | <iNum> <digit>
<digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<fNum> ::= + <digit> . <digit> <digit> E <digit> | - <digit> . <digit> <digit> E <digit> | + <digit> . <digit> <digit> E - <digit> | - <digit> . <digit> <digit> E - <digit>